### ISSUE TITLE
Error when loading dataset

### ISSUE THREAD

**Issue by chingfhen** [deepset-ai/COVID-QA#114]
Hi, 

I'm trying to load the dataset using this suggested code:

from datasets import load_dataset
dataset = load_dataset("covid_qa_deepset")

However, i get the following error:

FileNotFoundError: Couldn't find file locally at covid_qa_deepset\covid_qa_deepset.py, or remotely at https://raw.githubusercontent.com/huggingface/datasets/1.1.3/datasets/covid_qa_deepset/covid_qa_deepset.py or https://s3.amazonaws.com/datasets.huggingface.co/datasets/datasets/covid_qa_deepset/covid_qa_deepset.py

Would greatly appreciate some advice! Thanks!

**Comment by Timoeller** [comment]
Hey thanks for raising the issue here as well.

Did you see https://github.com/huggingface/datasets/issues/1641 there they say these datasets will be available with the next release or you install the latest master.
