### ISSUE TITLE
Where test dataset

### ISSUE THREAD

**Issue by Sotatek-ChienDao** [deepset-ai/COVID-QA#183]
Where do I get  the test dataset for COVIDQA?

**Comment by Timoeller** [comment]
Hey, thanks for your interest in the COVID-QA dataset.

Unfortunately there is no dedicated test data, we splitted away dev and test set from the dataset.
The scores you see reported are coming from 5 fold cross validation, so the whole dataset is used for training and evaluation (at some point).

**Comment by Sotatek-ChienDao** [comment]
thank you
