### ISSUE TITLE
Create english evaluation dataset for question similarity

### ISSUE THREAD

**Issue by tholor** [deepset-ai/COVID-QA#4]
We should create a simple, evaluation dataset that can be used to benchmark our models for matching similar questions. 

What should be sufficient for a rough baseline:
- 100-300 question pairs of similar questions
- extending that with 50% false pairs

**Comment by andra-pumnea** [comment]
How do you plan to go about labeling the data?

**Comment by Timoeller** [comment]
We are currently creating an English only dataset manually by rephrasing some of the questions.

The workflow is like this:
1. We scrape data from official FAQ sites with the data format explained in the readme.
2. We select a subset of these questions and create up to 3 rephrasings each. (You could do so for Romanian and work on improving Romanian Models yourself?)
3. We will create a folder to collect all eval data for everyone to use.
4. We are working on a way to add feedback inside the UI directly - this will be a more scalable way to collect data.

Happy to get your feedback on that or if you want to start with a scraper + adding manual labels for eval that would be a blast!

**Comment by tholor** [comment]
You can see our progress on the English eval dataset here: https://docs.google.com/spreadsheets/d/1kpTICmn-Ge5epfXzayNsMgC1JYZ4oTf6p-d3ZNsWYKU/edit?usp=sharing

If you want to contribute some rephrased questions (or a dataset for another language), just create a google spreadsheet / CSV similar to this :)

**Comment by tholor** [comment]
Done in #16 

Let's have separate issues for other languages.
