### ISSUE TITLE
NOT AN ISSUE  : I've created a Telegram Bot

### ISSUE THREAD

**Issue by theapache64** [deepset-ai/COVID-QA#55]
I've created a telegram bot to your web interface

https://t.me/corona_scholar_bot 

Can I add it to the README?

**Comment by Timoeller** [comment]
Yes totally you can. This is amazing!

**Comment by theapache64** [comment]
Thank you so much. I need some clarification regarding the API. Can you ping me @ http://t.me/theapache64 ?

**Comment by tholor** [comment]
Awesome! great work @theapache64 !

**Comment by theapache64** [comment]
Thank you @tholor . All credit goes to the team. I'll update the README ASAP.

**Comment by theapache64** [comment]
I've created a PR here -> https://github.com/deepset-ai/COVID-QA/pull/58 

It'd be awesome If u can take a look into it guys. 

@Timoeller @tholor
