### ISSUE TITLE
Frontend: giving Feedback results in tagging multiple ansers

### ISSUE THREAD

**Issue by David-Mueller** [deepset-ai/COVID-QA#59]
"I just wanted to 'like' the upper answer, but by clicking the button the second (incorrect) answer also was marked with a green like.
Question asked was "Wie lang ist die Inkubationszeit" or something similar."

The problem seems to be, that there answers have the same document_id.
We need some unique id for each answer - maybe paragraph_id?

Example:
paragraph_id:"HnLWAnEB3Qua7g62e99g"
document_id:"1"

**Comment by tholor** [comment]
@tanaysoni can you please have a look at this? I suppose it's due to wrong indexing in elasticsearch
