### ISSUE TITLE
Feature : Matched Question and Feedback Option

### ISSUE THREAD

**Issue by theapache64** [deepset-ai/COVID-QA#65]
Thanks again for creating this PR. Great work!

Two comments: 
- Right now the answer displayed by the bot doesn't contain the "matched question". However, it might be helpful for the users to see that in order to judge if the answer is really relevant to their question. You find it in the response JSON in the field "question". 
- We now also have the option for user feedback (see [API endpoint](https://github.com/deepset-ai/COVID-QA/blob/master/backend/controller/feedback.py)). So people can rate if the given answer was helpful or not and we will use the data to improve the NLP model. This could be also an helpful addition to the telegram bot. 

Would be great to hear your thoughts on that and maybe address them in a separate PR.

_Originally posted by @tholor in https://github.com/deepset-ai/COVID-QA/pull/58#issuecomment-602513354_

**Comment by theapache64** [comment]
@tholor 

I've updated the reply format to 

```kotlin
$emoji Answer Confidence : $confidence% 
Q: ${ans.question}
A: ${ans.answer}
🌍 Source : <a href="${ans.meta.link}">${ans.meta.source}</a>
```

Is this okay ?

**Comment by tholor** [comment]
Yes, perfect!

**Comment by theapache64** [comment]
one more format

```kotlin
Q: ${ans.question}
A: ${ans.answer}
💪 Answer Confidence : $confidence% $emoji 
🌍 Source : <a href="${ans.meta.link}">${ans.meta.source}</a>
```

Which one is better? first or this?

**Comment by theapache64** [comment]
Can u DM me at http://t.me/theapache64

**Comment by theapache64** [comment]
@tholor When I try to post the feedback, am getting

```json
{"detail":[{"loc":["body","request","questions"],"msg":"field required","type":"value_error.missing"}]}
```
from the server. 

The swagger doc says feedback API needs 4 params.
```
{
  "question": "string",
  "answer": "string",
  "feedback": "relevant",
  "document_id": 0
}
```

but the [python script](https://github.com/deepset-ai/COVID-QA/blob/master/backend/controller/feedback.py) only handles one.

I won't able to pass question and answer to the route, as Telegram only supports max **64bytes** of data via `callback_data`. [See here](https://core.telegram.org/bots/api#inlinekeyboardbutton)

**Comment by tholor** [comment]
@theapache64 yes, the API requires all four fields at the moment (and they are used in the python code you linked). Please also note that the value for **"question" must be the one asked by the user** and not the one we matched in the FAQs.  

I see your limitations with 64bytes and can think of two solutions:
1) short term: we make "answer" an optional field as we could get this also via the document_id. Could you test if you already fulfill the 64 bytes requirement with this?
2) mid term: if this is still more than 64bytes, we could probably introduce a unique request_id and then reduce the request to {"request_id": 123, "feedback": "relevant"}. However, for this, we need quite some changes in our backend and the indexing in elastic.

**Comment by theapache64** [comment]
Perfect. For now, we can go with the short term solution, but if the question is lengthy (more than 64bytes), the feedback won't be posted. I'd suggest you work on the midterm solution ASAP. Otherwise, we may lose some valuable feedback. What do you say? 

and How much time do you need to make the `answer` variable optional?

**Comment by tholor** [comment]
> How much time do you need to make the answer variable optional?

Implemented in #69. We can deploy it in the next hours. Will let you know once that's done.

> I'd suggest you work on the midterm solution ASAP

Yes, we will tackle that. Can't promise a timeline though as most of us work in their regular jobs during the week.

**Comment by tholor** [comment]
@theapache64 latest master is deployed now (incl. the optional `answer` field)

**Comment by theapache64** [comment]
![image](https://user-images.githubusercontent.com/9678279/77419613-bd12ee80-6dee-11ea-9efc-eb12e5fe7ece.png)

It's done! Any changes? @tholor

**Comment by tholor** [comment]
Looking great! Thank you @theapache64
