### ISSUE TITLE
BMAS-Scraper not working

### ISSUE THREAD

**Issue by bogdankostic** [deepset-ai/COVID-QA#66]
It seems that the [BMAS-Scraper](https://github.com/deepset-ai/COVID-QA/blob/master/data/scrapers/BMAS_scraper.py) is not properly working. 

The problem seems to be with extracting the questions. The resulting question column contains three empty strings.

**Comment by tkh42** [comment]
Yes, they changed the structure of the website. I will update the question extraction.
