### ISSUE TITLE
Question : API

### ISSUE THREAD

**Issue by theapache64** [deepset-ai/COVID-QA#70]
I've been [developing](https://github.com/deepset-ai/COVID-QA/pull/58) a telegram bot using the API. Currently am using `https://covid-middleware.deepset.ai/api/bert/question` to get the answers.

```curl
curl -X POST \
  https://covid-middleware.deepset.ai/api/bert/question \
  -H 'content-type: application/json' \
  -d '{
	"question":"community spread?"
}'
```

but the [swagger](http://3.121.62.187/docs) doesn't list this API and shows a [different one](https://covid-backend.deepset.ai/docs#/model/ask_models__model_id__doc_qa_post) with different structures. 

So, my question is, Which API should I choose to get the answers? @tanaysoni

**Comment by tanaysoni** [comment]
Hi @theapache64, during the hackathon, the middleware was deprecated. The new updated APIs are available at https://covid-backend.deepset.ai. The documentation is at https://covid-backend.deepset.ai/docs. 

I hope that clears the confusion.

**Comment by theapache64** [comment]
Alright. 

Can you explain the parameters ? 

```json
{
  "questions": [
    "string"
  ],
  "filters": {
    "additionalProp1": "string",
    "additionalProp2": "string",
    "additionalProp3": "string"
  },
  "top_k_reader": 0,
  "top_k_retriever": 0
}
```

**Comment by sfakir** [comment]
@tanaysoni 
I propose we hide the "model" from the the clients. because it's not responsibility of the clients to know what kind of models were used in the backend.

I create an MR to have a unified endpoint and internally we route to the right model, what do you think?

**Comment by tanaysoni** [comment]
@theapache64, a sample request looks like this:

```
{
    "questions": ["what are the symptoms?"],
    "top_k_retriever": 5 // return top 5 answers
}
```
The `top_k_reader` [parameter](https://github.com/deepset-ai/haystack/blob/9897c40c41780ed500e51801c4c5d92c549f9351/haystack/finder.py#L20) can be ignored for FAQ style Question Answering. 

With the current version, filters are tricky to implement as there's no endpoint to get a list of available filters. Feel free to create a PR if that's something useful for your use case!

**Comment by sfakir** [comment]
@tanaysoni  In MR74 I added POST /question/ask 
as a proxy endpoint for our models. 

It's my recommendation to have this very abstract endpoint we can keep and there won't be a change later, also we are able then to change the model internally without notifying all clients. We can have a chat about this later on.

**Comment by theapache64** [comment]
@tanaysoni Which model should I use ? `1` or `2` ?

**Comment by tanaysoni** [comment]
@sfakir a unified endpoint sounds good to me! 

I would propose to keep both, the unified endpoint and model-specific endpoints. 

In the unified endpoint, we detect language of the request and route it to the appropriate model. For advanced use cases, clients can choose between the model-specific endpoints.

**Comment by tanaysoni** [comment]
@theapache64 model `1` is multi-lingual, while model `2` is exclusive English. If you're working only with English then model `2` might have better results.

**Comment by theapache64** [comment]
@tanaysoni Which languages are supported in model 1?

**Comment by tholor** [comment]
In theory, it's multilingual. In practice, we only have reasonable amount of FAQ data for German and English right now. 

We are currently switching to a generic API endpoint (see https://github.com/deepset-ai/COVID-QA/pull/72). So please use `/question/ask` once it's deployed (without any model id). We will then take care of routing it to the best model available for the detected language.
