### ISSUE TITLE
Getting empty answer

### ISSUE THREAD

**Issue by theapache64** [deepset-ai/COVID-QA#75]
![image](https://user-images.githubusercontent.com/9678279/77569846-db611300-6ef0-11ea-9d9d-421a87bb1c8f.png)

**Comment by tholor** [comment]
Found 10 FAQs with empty answers indexed in elasticsearch. Deleted them now. 
@bogdankostic Can you please filter out scraper results that have an empty answer string to avoid something like this in the future?

**Comment by bogdankostic** [comment]
@tholor 
The meta-scraper is already filtering out empty answers (see [here](https://github.com/deepset-ai/COVID-QA/blob/master/datasources/META_scraper.py#L24)). 
I checked the resulting dataframe for empty strings, but none of the answer cells is empty. Also, I checked whether there are answer cells which only contain whitespace (thus not being technically empty), but this is not the case either.
