### ISSUE TITLE
Gitter Chat Room community for COVID-QA Projects

### ISSUE THREAD

**Issue by tonyreina** [deepset-ai/COVID-QA#77]
I started a chat room on Gitter to help us coordinate the projects. Please sign up at https://gitter.im/COVID-QA/community?utm_source=share-link&utm_medium=link&utm_campaign=share-link

**Comment by tholor** [comment]
Great! Thanks @tonyreina. I will add the link to the readme. We should try to keep all code-related discussions in the GitHub Issues and use Gitter only for the topics that don't work well in Issues (e.g. higher-level planning/coordination, quick chats of people working together on an issue ...)
