### ISSUE TITLE
Allow sending a query by pressing enter

### ISSUE THREAD

**Issue by tholor** [deepset-ai/COVID-QA#8]
Sending the query via enter doesn't work anymore (tested in chrome). 

@sfakir didn't you already implement this?

**Comment by sfakir** [comment]
@tholor  yes was alraedy implemented, but looks like Julia removed this in the commit adding the brain. Not sure why, I'll add this again

**Comment by sfakir** [comment]
Ah I think this is connected to the autocomplete, since enter selects now the "selected autocomplete" value.
I  can ask Julia if we can detect if an autocomplete value is selected and if not do a regular submit (or try it myself.)

**Comment by Timoeller** [comment]
This seems kind of solved, closing it now.
