### ISSUE TITLE
CDC Water Scraper Error

### ISSUE THREAD

**Issue by mfleming99** [deepset-ai/COVID-QA#96]
https://github.com/deepset-ai/COVID-QA/blob/4890ad52da357926f1b27dfa6ccd3daf9fde49ae/datasources/scrapers/CDC_Water_scraper.py#L51

This line in the CDC_Water_scraper will cause an error.
```
UnboundLocalError: local variable 'current_question' referenced before assignment
```
It seems that lines https://github.com/deepset-ai/COVID-QA/blob/4890ad52da357926f1b27dfa6ccd3daf9fde49ae/datasources/scrapers/CDC_Water_scraper.py#L51-L53 should be deleted.

**Comment by bogdankostic** [comment]
The page structure changed, I will adapt the script to the new structure.
